apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-serviceaccount
  namespace: default
imagePullSecrets:
  - name: myregistrykey
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
 name: sa-secret
 annotations:
  kubernetes.io/service-account.name: "sample-serviceaccount"