apiVersion: v1
kind: Pod
metadata:
  name: sample-secret-multi-env
spec:
  containers:
  - name: secret-container
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - secretRef:
          name: sample-db-auth
    ports:
      - containerPort: 8080
