apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-multi-volume
  labels:
    name: sample-configmap-multi-volume
spec:
  containers:
  - name: configmap-container
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /config
        name: config-volume
    ports:
      - containerPort: 8080
  volumes:
    - name: config-volume
      configMap:
        name: sample-configmap
