apiVersion: v1
kind: Pod
metadata:
  name: sample-configmap-multi-env
  labels:
    name: sample-configmap-multi-env
spec:
  containers:
  - name: configmap-container
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: sample-configmap
    ports:
      - containerPort: 8080
