apiVersion: v1
kind: Pod
metadata:
  name: sample-emptydir
  labels:
    name: sample-emptydir
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    volumeMounts:
      - mountPath: /cache
        name: cache-volume
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  volumes:
    - name: cache-volume
      emptyDir:
        medium: Memory
        sizeLimit: 128Mi
