apiVersion: v1
kind: Pod
metadata:
  name: sample-2pod-fail
spec:
  containers:
  - name: nginx-container-112
    image: nginx:1.16
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
  - name: nginx-container-113
    image: nginx:1.16
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
