apiVersion: v1
kind: Pod
metadata:
  name: sample-hostnetwork
spec:
  hostNetwork: true
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
