apiVersion: v1
kind: Pod
metadata:
  name: sample-2pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
  - name: redis-container
    image: redis:3.2
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
