apiVersion: v1
kind: Pod
metadata:
  name: sample-entrypoint
spec:
  containers:
  - name: nginx-container-112
    image: nginx:1.16
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
    command: ["/bin/sleep"] # ENTRYPOINTに対応
    args: ["3600"] # CMD命令に対応
