apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-vpa-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: vpa-container
        image: amsy810/tools:v2.0
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
      - name: no-vpa-container
        image: amsy810/tools:v2.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
