apiVersion: v1
kind: Pod
metadata:
  name: sample-annotations
  annotations:
    annotation1: val1
    annotation2: "200"  # 数値を利用する場合はダブルクォーテーションで囲う
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      limits:
        memory: "20Mi"
        cpu: "1"
