apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  nodeName: kindcluster-worker
  containers:
  - name: nginx-container
    image: nginx:1.17
    resources:
      limits:
        cpu: "1"
        memory: "20Mi"